version: '2'
services:
  elastic:
    image: elasticsearch:6.4.0
    container_name: elastic
    restart: always
    environment:
      - hostname=elastic
      - "discovery.type=single-node"
    ulimits:
      memlock:
soft: -1
hard: -1
    volumes:
      - ./elasticdata:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
      
  kibana:
    image: kibana:6.4.0
    container_name: kibana
    restart: always
    environment:
      - hostname=kibana
    ports:
      - 5601:5601
    links:
      - elastic:elasticsearch
    depends_on:
      - elastic

